#!/bin/bash
# Compile script for ZOModel

#Print ZOModel title
echo ""
echo "#####################################"
echo "#                                   #"
echo "# ZOModel: Zombie Outbreak Modeling #"
echo "#                                   #"
echo "#####################################"
echo ""

### Compile ZOModel ###
echo "Compiling the ZOModel binary..."
cd src/
g++ -fopenmp -g -static -O3 ZOModel.cpp -o ZOModel
cd ../
mv src/ZOModel .
echo ""

### Finish ###
echo "Done."
echo ""
